const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")
const { zodToJsonSchema } = require("zod-to-json-schema")
const puppeteer = require("puppeteer")
const { nativeGeminiSchema } = require("../utils/aiResponseSchema")

const ai = new GoogleGenAI({
	apiKey: process.env.GOOGLE_GENAI_API_KEY
})


async function generateInterviewReport({ resume, selfDescription, jobDescription }) {


	// Notice how clean the prompt is now. No JSON templates!
	const prompt = `
# Role
You are an elite, highly critical Technical Recruiter and Senior Engineering Manager. 

# Objective
Analyze the provided candidate profile against the Job Description to generate a rigorous, highly specific interview preparation report. Do not use generic filler advice.

# Data Sources
- **Candidate Resume:** ${resume}

- **Candidate Self-Description:** ${selfDescription}

- **Target Job Description:** ${jobDescription}

# Instructions for Content Quality
1. **Match Score:** Be ruthlessly objective. Do not give a 90% match if they lack core requirements. 
2. **Technical Questions:** Base these on the exact tech stack mentioned in the JD. Make them scenario-based, not just textbook definitions.
3. **Skill Gaps:** Cross-reference the resume against every requirement in the JD. If a required skill isn't on the resume, log it as a gap.
4. **Preparation Plan:** Create a targeted 7-day sprint that specifically attacks the identified 'Skill Gaps' and prepares them for the 'Technical Questions'.
`;
	try {
		const response = await ai.models.generateContent({
			model: "gemini-3-flash-preview", // Note: Ensure you are using a valid model string for your SDK version
			contents: [{
				role: "user",
				parts: [{ text: prompt }]
			}],
			config: {
				// This guarantees the output is JSON
				responseMimeType: "application/json",
				// This forces the AI to map its answers to your exact keys and types
				responseSchema: nativeGeminiSchema(),
				// Optional: Slightly lower temperature for more deterministic/factual output
				temperature: 0.4,
			}
		});

		// Parse and return the flawlessly structured JSON
		return JSON.parse(response.text);

	} catch (error) {
		console.error("AI Generation Error:", error);
		throw new Error("Failed to generate the interview report via AI.");
	}


}



async function generatePdfFromHtml(htmlContent) {
	const browser = await puppeteer.launch()
	const page = await browser.newPage();
	await page.setContent(htmlContent, { waitUntil: "networkidle0" })

	const pdfBuffer = await page.pdf({
		format: "A4", margin: {
			top: "20mm",
			bottom: "20mm",
			left: "15mm",
			right: "15mm"
		}
	})

	await browser.close()

	return pdfBuffer
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {

	const resumePdfSchema = z.object({
		html: z.string().describe("The HTML content of the resume which can be converted to PDF using any library like puppeteer")
	})

	const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

	const response = await ai.models.generateContent({
		model: "gemini-3-flash-preview",
		contents: prompt,
		config: {
			responseMimeType: "application/json",
			responseSchema: zodToJsonSchema(resumePdfSchema),
		}
	})


	const jsonContent = JSON.parse(response.text)

	const pdfBuffer = await generatePdfFromHtml(jsonContent.html)

	return pdfBuffer

}

module.exports = { generateInterviewReport, generateResumePdf }